root_ca: /home/pi/certs/Amazon-root-CA-1.pem
cert: /home/pi/certs/device.pem.crt
priv_key: /home/pi/certs/private.pem.key
pub_key: /home/pi/certs/public.pem.key

thing_endpoint: a2cu3nec9xctuz-ats.iot.us-west-2.amazonaws.com
client_id: discoPi

topic: discoPi/+

power_strip_name: TP-LINK_Smart Plug_8817
discolights_plug_name: Disco Light
discoball_plug_name: Discoball

spotify_disco_playlist_urn: 4S7Yk4oYushiMYoChvV6SJ